[package]
name = "YangMillsMassGap"
version = "1.0.0"
keywords = ["mathematics", "physics", "yang-mills", "mass-gap", "millennium-problem"]
description = "Formal verification of Yang-Mills Mass Gap proof via Distributed Consciousness"

[[lean_lib]]
name = "YangMills"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib4.git", rev = "v4.8.0"}

[require_deps]

